### PR TITLE
Ch improve user experience 160807921

### PR DESCRIPTION
**Pull request by SokoPaulSokool**
#### What does this PR do?
Improves the user experience as a response to the feedback from my LFA

#### Description of Task completed?
I have added some extra signup button
Removed unused button in the navigation menu
Centered titles
Made model fill the viewport
Properly aligned fields in the forms

### CODE REVIEW

**Comment by mozzy22** [comment]
looks pretty cool. u can try this validator to do more validations of your HTML structure  https://validator.w3.org/#validate_by_input

**Comment by walimike** [comment]
Thumbs up Paul, I think this is okay.

**Comment by arthurarty** [comment]
Interesting class names. Otherwise good stuff.

**Comment by Evie-ey** [comment]
Your work is organised

**Pull request merged**
