### PR TITLE
Ft ch1 admin add orders 160315664

### PR DESCRIPTION
**Pull request by SokoPaulSokool**
hi @sekayasin, @Gfreedoms, @kdaglas, @Gfreedoms   check out my site and see what I have left.
I feel I have made it responsive. Check it 
https://sokopaulsokool.github.io/andela_fast_food_fast/UI/

### CODE REVIEW

**Comment by sekayasin** [comment]
Wawwu bro! Yap! i have tested the responsiveness, bravo! it tastes like chicken! .. shadow effects on hover of the menu items are super Awesome!

**Comment by kdaglas** [comment]
its surely responsive

**Comment by mozzy22** [comment]
cool work , just improve on the responsivenes  of the home page

**Comment by jeanjoe** [comment]
Great work, ensure there are are no html tags within the select `option` tag, I am seeing `<option><h4>Customer</h4></option>`

**Pull request merged**
